// Generated by gencpp from file car_agilex/LightState.msg
// DO NOT EDIT!


#ifndef CAR_AGILEX_MESSAGE_LIGHTSTATE_H
#define CAR_AGILEX_MESSAGE_LIGHTSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace car_agilex
{
template <class ContainerAllocator>
struct LightState_
{
  typedef LightState_<ContainerAllocator> Type;

  LightState_()
    : mode(0)
    , custom_value(0)  {
    }
  LightState_(const ContainerAllocator& _alloc)
    : mode(0)
    , custom_value(0)  {
  (void)_alloc;
    }



   typedef uint8_t _mode_type;
  _mode_type mode;

   typedef uint8_t _custom_value_type;
  _custom_value_type custom_value;





  typedef boost::shared_ptr< ::car_agilex::LightState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::car_agilex::LightState_<ContainerAllocator> const> ConstPtr;

}; // struct LightState_

typedef ::car_agilex::LightState_<std::allocator<void> > LightState;

typedef boost::shared_ptr< ::car_agilex::LightState > LightStatePtr;
typedef boost::shared_ptr< ::car_agilex::LightState const> LightStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::car_agilex::LightState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::car_agilex::LightState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::car_agilex::LightState_<ContainerAllocator1> & lhs, const ::car_agilex::LightState_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode &&
    lhs.custom_value == rhs.custom_value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::car_agilex::LightState_<ContainerAllocator1> & lhs, const ::car_agilex::LightState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace car_agilex

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::car_agilex::LightState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_agilex::LightState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::car_agilex::LightState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::car_agilex::LightState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_agilex::LightState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_agilex::LightState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::car_agilex::LightState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "51866248399dda20e62f6b250914288e";
  }

  static const char* value(const ::car_agilex::LightState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x51866248399dda20ULL;
  static const uint64_t static_value2 = 0xe62f6b250914288eULL;
};

template<class ContainerAllocator>
struct DataType< ::car_agilex::LightState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "car_agilex/LightState";
  }

  static const char* value(const ::car_agilex::LightState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::car_agilex::LightState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 mode\n"
"uint8 custom_value\n"
;
  }

  static const char* value(const ::car_agilex::LightState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::car_agilex::LightState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
      stream.next(m.custom_value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LightState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::car_agilex::LightState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::car_agilex::LightState_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "custom_value: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.custom_value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAR_AGILEX_MESSAGE_LIGHTSTATE_H
