// Generated by gencpp from file car_agilex/ScoutLightCmd.msg
// DO NOT EDIT!


#ifndef CAR_AGILEX_MESSAGE_SCOUTLIGHTCMD_H
#define CAR_AGILEX_MESSAGE_SCOUTLIGHTCMD_H

#include <ros/service_traits.h>


#include <car_agilex/ScoutLightCmdRequest.h>
#include <car_agilex/ScoutLightCmdResponse.h>


namespace car_agilex
{

struct ScoutLightCmd
{

typedef ScoutLightCmdRequest Request;
typedef ScoutLightCmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ScoutLightCmd
} // namespace car_agilex


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::car_agilex::ScoutLightCmd > {
  static const char* value()
  {
    return "2047fb36251c93f820b26cd1be3ecace";
  }

  static const char* value(const ::car_agilex::ScoutLightCmd&) { return value(); }
};

template<>
struct DataType< ::car_agilex::ScoutLightCmd > {
  static const char* value()
  {
    return "car_agilex/ScoutLightCmd";
  }

  static const char* value(const ::car_agilex::ScoutLightCmd&) { return value(); }
};


// service_traits::MD5Sum< ::car_agilex::ScoutLightCmdRequest> should match
// service_traits::MD5Sum< ::car_agilex::ScoutLightCmd >
template<>
struct MD5Sum< ::car_agilex::ScoutLightCmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::car_agilex::ScoutLightCmd >::value();
  }
  static const char* value(const ::car_agilex::ScoutLightCmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::car_agilex::ScoutLightCmdRequest> should match
// service_traits::DataType< ::car_agilex::ScoutLightCmd >
template<>
struct DataType< ::car_agilex::ScoutLightCmdRequest>
{
  static const char* value()
  {
    return DataType< ::car_agilex::ScoutLightCmd >::value();
  }
  static const char* value(const ::car_agilex::ScoutLightCmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::car_agilex::ScoutLightCmdResponse> should match
// service_traits::MD5Sum< ::car_agilex::ScoutLightCmd >
template<>
struct MD5Sum< ::car_agilex::ScoutLightCmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::car_agilex::ScoutLightCmd >::value();
  }
  static const char* value(const ::car_agilex::ScoutLightCmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::car_agilex::ScoutLightCmdResponse> should match
// service_traits::DataType< ::car_agilex::ScoutLightCmd >
template<>
struct DataType< ::car_agilex::ScoutLightCmdResponse>
{
  static const char* value()
  {
    return DataType< ::car_agilex::ScoutLightCmd >::value();
  }
  static const char* value(const ::car_agilex::ScoutLightCmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAR_AGILEX_MESSAGE_SCOUTLIGHTCMD_H
