// Generated by gencpp from file car_agilex/ScoutMotionCmd.msg
// DO NOT EDIT!


#ifndef CAR_AGILEX_MESSAGE_SCOUTMOTIONCMD_H
#define CAR_AGILEX_MESSAGE_SCOUTMOTIONCMD_H

#include <ros/service_traits.h>


#include <car_agilex/ScoutMotionCmdRequest.h>
#include <car_agilex/ScoutMotionCmdResponse.h>


namespace car_agilex
{

struct ScoutMotionCmd
{

typedef ScoutMotionCmdRequest Request;
typedef ScoutMotionCmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ScoutMotionCmd
} // namespace car_agilex


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::car_agilex::ScoutMotionCmd > {
  static const char* value()
  {
    return "cda17c11be66f27fe21573aa44658f84";
  }

  static const char* value(const ::car_agilex::ScoutMotionCmd&) { return value(); }
};

template<>
struct DataType< ::car_agilex::ScoutMotionCmd > {
  static const char* value()
  {
    return "car_agilex/ScoutMotionCmd";
  }

  static const char* value(const ::car_agilex::ScoutMotionCmd&) { return value(); }
};


// service_traits::MD5Sum< ::car_agilex::ScoutMotionCmdRequest> should match
// service_traits::MD5Sum< ::car_agilex::ScoutMotionCmd >
template<>
struct MD5Sum< ::car_agilex::ScoutMotionCmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::car_agilex::ScoutMotionCmd >::value();
  }
  static const char* value(const ::car_agilex::ScoutMotionCmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::car_agilex::ScoutMotionCmdRequest> should match
// service_traits::DataType< ::car_agilex::ScoutMotionCmd >
template<>
struct DataType< ::car_agilex::ScoutMotionCmdRequest>
{
  static const char* value()
  {
    return DataType< ::car_agilex::ScoutMotionCmd >::value();
  }
  static const char* value(const ::car_agilex::ScoutMotionCmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::car_agilex::ScoutMotionCmdResponse> should match
// service_traits::MD5Sum< ::car_agilex::ScoutMotionCmd >
template<>
struct MD5Sum< ::car_agilex::ScoutMotionCmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::car_agilex::ScoutMotionCmd >::value();
  }
  static const char* value(const ::car_agilex::ScoutMotionCmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::car_agilex::ScoutMotionCmdResponse> should match
// service_traits::DataType< ::car_agilex::ScoutMotionCmd >
template<>
struct DataType< ::car_agilex::ScoutMotionCmdResponse>
{
  static const char* value()
  {
    return DataType< ::car_agilex::ScoutMotionCmd >::value();
  }
  static const char* value(const ::car_agilex::ScoutMotionCmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAR_AGILEX_MESSAGE_SCOUTMOTIONCMD_H
