(cl:in-package car_agilex-msg)
(cl:export '(BASE_STATE-VAL
          BASE_STATE
          CONTROL_MODE-VAL
          CONTROL_MODE
          FAULT_CODE-VAL
          FAULT_CODE
          BATTERY_VOLTAGE-VAL
          BATTERY_VOLTAGE
          ACTUATOR_STATES-VAL
          ACTUATOR_STATES
          LIGHT_CONTROL_ENABLED-VAL
          LIGHT_CONTROL_ENABLED
          FRONT_LIGHT_STATE-VAL
          FRONT_LIGHT_STATE
          REAR_LIGHT_STATE-VAL
          REAR_LIGHT_STATE
          LINEAR_VELOCITY-VAL
          LINEAR_VELOCITY
          ANGULAR_VELOCITY-VAL
          ANGULAR_VELOCITY
          LEFT_ODOMETRY-VAL
          LEFT_ODOMETRY
          RIGHT_ODOMETRY-VAL
          RIGHT_ODOMETRY
))