// Generated by gencpp from file RBAC/accessResponse.msg
// DO NOT EDIT!


#ifndef RBAC_MESSAGE_ACCESSRESPONSE_H
#define RBAC_MESSAGE_ACCESSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace RBAC
{
template <class ContainerAllocator>
struct accessResponse_
{
  typedef accessResponse_<ContainerAllocator> Type;

  accessResponse_()
    : result(false)
    , message()  {
    }
  accessResponse_(const ContainerAllocator& _alloc)
    : result(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::RBAC::accessResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::RBAC::accessResponse_<ContainerAllocator> const> ConstPtr;

}; // struct accessResponse_

typedef ::RBAC::accessResponse_<std::allocator<void> > accessResponse;

typedef boost::shared_ptr< ::RBAC::accessResponse > accessResponsePtr;
typedef boost::shared_ptr< ::RBAC::accessResponse const> accessResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::RBAC::accessResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::RBAC::accessResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::RBAC::accessResponse_<ContainerAllocator1> & lhs, const ::RBAC::accessResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::RBAC::accessResponse_<ContainerAllocator1> & lhs, const ::RBAC::accessResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace RBAC

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::RBAC::accessResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RBAC::accessResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::RBAC::accessResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::RBAC::accessResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RBAC::accessResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RBAC::accessResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::RBAC::accessResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b543fbd3518c791be28589b850702201";
  }

  static const char* value(const ::RBAC::accessResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb543fbd3518c791bULL;
  static const uint64_t static_value2 = 0xe28589b850702201ULL;
};

template<class ContainerAllocator>
struct DataType< ::RBAC::accessResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "RBAC/accessResponse";
  }

  static const char* value(const ::RBAC::accessResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::RBAC::accessResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool result\n"
"string message\n"
;
  }

  static const char* value(const ::RBAC::accessResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::RBAC::accessResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct accessResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::RBAC::accessResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::RBAC::accessResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RBAC_MESSAGE_ACCESSRESPONSE_H
