# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from car_agilex/ActuatorState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ActuatorState(genpy.Message):
  _md5sum = "9fbd9d68394311e2609797770a9092c6"
  _type = "car_agilex/ActuatorState"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 motor_current
float64 motor_rpm
uint16 motor_pulses
float64 motor_temperature

float64 driver_voltage
float64 driver_temperature
uint8 driver_state"""
  __slots__ = ['motor_current','motor_rpm','motor_pulses','motor_temperature','driver_voltage','driver_temperature','driver_state']
  _slot_types = ['float64','float64','uint16','float64','float64','float64','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       motor_current,motor_rpm,motor_pulses,motor_temperature,driver_voltage,driver_temperature,driver_state

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ActuatorState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.motor_current is None:
        self.motor_current = 0.
      if self.motor_rpm is None:
        self.motor_rpm = 0.
      if self.motor_pulses is None:
        self.motor_pulses = 0
      if self.motor_temperature is None:
        self.motor_temperature = 0.
      if self.driver_voltage is None:
        self.driver_voltage = 0.
      if self.driver_temperature is None:
        self.driver_temperature = 0.
      if self.driver_state is None:
        self.driver_state = 0
    else:
      self.motor_current = 0.
      self.motor_rpm = 0.
      self.motor_pulses = 0
      self.motor_temperature = 0.
      self.driver_voltage = 0.
      self.driver_temperature = 0.
      self.driver_state = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2dH3dB().pack(_x.motor_current, _x.motor_rpm, _x.motor_pulses, _x.motor_temperature, _x.driver_voltage, _x.driver_temperature, _x.driver_state))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 43
      (_x.motor_current, _x.motor_rpm, _x.motor_pulses, _x.motor_temperature, _x.driver_voltage, _x.driver_temperature, _x.driver_state,) = _get_struct_2dH3dB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2dH3dB().pack(_x.motor_current, _x.motor_rpm, _x.motor_pulses, _x.motor_temperature, _x.driver_voltage, _x.driver_temperature, _x.driver_state))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 43
      (_x.motor_current, _x.motor_rpm, _x.motor_pulses, _x.motor_temperature, _x.driver_voltage, _x.driver_temperature, _x.driver_state,) = _get_struct_2dH3dB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2dH3dB = None
def _get_struct_2dH3dB():
    global _struct_2dH3dB
    if _struct_2dH3dB is None:
        _struct_2dH3dB = struct.Struct("<2dH3dB")
    return _struct_2dH3dB
