// Generated by gencpp from file OTA/msg.msg
// DO NOT EDIT!


#ifndef OTA_MESSAGE_MSG_H
#define OTA_MESSAGE_MSG_H

#include <ros/service_traits.h>


#include <OTA/msgRequest.h>
#include <OTA/msgResponse.h>


namespace OTA
{

struct msg
{

typedef msgRequest Request;
typedef msgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct msg
} // namespace OTA


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::OTA::msg > {
  static const char* value()
  {
    return "c86ebe885efd9f142a198542f73f2d7f";
  }

  static const char* value(const ::OTA::msg&) { return value(); }
};

template<>
struct DataType< ::OTA::msg > {
  static const char* value()
  {
    return "OTA/msg";
  }

  static const char* value(const ::OTA::msg&) { return value(); }
};


// service_traits::MD5Sum< ::OTA::msgRequest> should match
// service_traits::MD5Sum< ::OTA::msg >
template<>
struct MD5Sum< ::OTA::msgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::OTA::msg >::value();
  }
  static const char* value(const ::OTA::msgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::OTA::msgRequest> should match
// service_traits::DataType< ::OTA::msg >
template<>
struct DataType< ::OTA::msgRequest>
{
  static const char* value()
  {
    return DataType< ::OTA::msg >::value();
  }
  static const char* value(const ::OTA::msgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::OTA::msgResponse> should match
// service_traits::MD5Sum< ::OTA::msg >
template<>
struct MD5Sum< ::OTA::msgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::OTA::msg >::value();
  }
  static const char* value(const ::OTA::msgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::OTA::msgResponse> should match
// service_traits::DataType< ::OTA::msg >
template<>
struct DataType< ::OTA::msgResponse>
{
  static const char* value()
  {
    return DataType< ::OTA::msg >::value();
  }
  static const char* value(const ::OTA::msgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OTA_MESSAGE_MSG_H
