// Generated by gencpp from file OTA/msgRequest.msg
// DO NOT EDIT!


#ifndef OTA_MESSAGE_MSGREQUEST_H
#define OTA_MESSAGE_MSGREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace OTA
{
template <class ContainerAllocator>
struct msgRequest_
{
  typedef msgRequest_<ContainerAllocator> Type;

  msgRequest_()
    : request()  {
    }
  msgRequest_(const ContainerAllocator& _alloc)
    : request(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _request_type;
  _request_type request;





  typedef boost::shared_ptr< ::OTA::msgRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::OTA::msgRequest_<ContainerAllocator> const> ConstPtr;

}; // struct msgRequest_

typedef ::OTA::msgRequest_<std::allocator<void> > msgRequest;

typedef boost::shared_ptr< ::OTA::msgRequest > msgRequestPtr;
typedef boost::shared_ptr< ::OTA::msgRequest const> msgRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::OTA::msgRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::OTA::msgRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::OTA::msgRequest_<ContainerAllocator1> & lhs, const ::OTA::msgRequest_<ContainerAllocator2> & rhs)
{
  return lhs.request == rhs.request;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::OTA::msgRequest_<ContainerAllocator1> & lhs, const ::OTA::msgRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace OTA

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::OTA::msgRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::OTA::msgRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::OTA::msgRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::OTA::msgRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::OTA::msgRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::OTA::msgRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::OTA::msgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "225c0d3ce5e24840699723eab85d371d";
  }

  static const char* value(const ::OTA::msgRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x225c0d3ce5e24840ULL;
  static const uint64_t static_value2 = 0x699723eab85d371dULL;
};

template<class ContainerAllocator>
struct DataType< ::OTA::msgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "OTA/msgRequest";
  }

  static const char* value(const ::OTA::msgRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::OTA::msgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8[] request\n"
;
  }

  static const char* value(const ::OTA::msgRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::OTA::msgRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.request);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msgRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::OTA::msgRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::OTA::msgRequest_<ContainerAllocator>& v)
  {
    s << indent << "request[]" << std::endl;
    for (size_t i = 0; i < v.request.size(); ++i)
    {
      s << indent << "  request[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.request[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OTA_MESSAGE_MSGREQUEST_H
