# DWAPlannerROS:
#   max_vel_trans: 0.50
#   min_vel_trans: 0.01
#   max_vel_x: 0.40
#   min_vel_x: -0.025
#   max_vel_y: 0.0
#   min_vel_y: 0.0
#   max_vel_theta: 0.20
#   min_vel_theta: -0.20
#   acc_lim_x: 1.0
#   acc_lim_y: 0.0
#   acc_lim_th: 5
#   acc_lim_trans: 1.25

#   prune_plan: false

#   # xy_goal_tolerance: 0.15 #0.25
#   xy_goal_tolerance: 0.2
#   # yaw_goal_tolerance: 0.1 #0.1
#   yaw_goal_tolerance: 0.1
#   yaw_goal_tolerance: 0.1 #0.1
#   trans_stopped_vel: 0.1
#   theta_stopped_vel: 0.1
#   sim_time: 2.0
#   sim_granularity: 0.1
#   angular_sim_granularity: 0.1
#   pdist_scale: 0.6
#   gdist_scale: 0.8
#   path_distance_bias: 34.0
#   goal_distance_bias: 24.0
#   # occdist_scale: 0.01
#   occdist_scale: 0.2
#   twirling_scale: 0.0
#   stop_time_buffer: 0.5
#   oscillation_reset_dist: 0.05
#   oscillation_reset_angle: 0.2
#   forward_point_distance: 0.3
#   scaling_speed: 0.25
#   max_scaling_factor: 0.2
#   vx_samples: 20
#   vy_samples: 0
#   vth_samples: 40

#   use_dwa: true
#   restore_defaults: false

TebLocalPlannerROS:
  odom_topic:   odom         
  map_frame:    odom     

  max_vel_x: 0.35
  min_vel_x: -0.025
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_vel_theta: 10.20
  min_vel_theta: -10.20
  acc_lim_x: 1.0
  acc_lim_y: 0.0
  acc_lim_th: 7
  xy_goal_tolerance: 0.34
  yaw_goal_tolerance: 0.39

  min_turning_radius: 0.0
  wheelbase: 0.0
  cmd_angle_instead_rotvel: false
  is_footprint_dynamic: false
  dwa: true
  dwa_oscillation_reset_dist: 0.05
  dwa_oscillation_reset_angle: 0.2
  publish_feedback: false
  # # HCP
  # hcp: false
  # # Recovery
  # recovery_behavior_enabled: true
  # clearing_rotation_allowed: true
  # recovery_behaviors:
  #   - name: conservative_reset
  #     type: clear_costmap_recovery/ClearCostmapRecovery
  #   - name: aggressive_reset
  #     type: clear_costmap_recovery/ClearCostmapRecovery
  #   - name: rotate_recovery
  #     type: rotate_recovery/RotateRecovery

  # Visualization
  visualization: true
  publish_diagnostics: false
  teb_poses_clearing: true
  teb_poses_clearing_delay: 2.0
  global_plan_viz: true
  global_plan_viz_skip: 0
  teb_poses_viz: false
  teb_poses_text: false
  teb_marker_color: magenta
  teb_marker_scale: 0.1
  alternative_time_cost: false
  enable_homotopy_class_planning: false
  enable_multithreading: true
  simple_exploration: false
  max_number_classes: 4
  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 5
  h_signature_prescaler: 0.5
  h_signature_threshold: 0.1
  obstacle_keypoint_offset: 0.1
  obstacle_heading_threshold: 0.45
  visualize_hc_graph: false

  # Trajectory params
  teb_autosize: True         
  dt_ref:    0.13
  dt_hysteresis:   0.05
  min_samples:     2
  max_samples:     500
  force_reinit_new_goal_dist:       1.0
  global_plan_overwrite_orientation: True
  global_plan_viapoint_sep:          -0.1
  max_global_plan_lookahead_dist:    3.0
  force_reinit_new_goal_dist:         1.0
  feasibility_check_no_poses:       5
  publish_feedback:      false
  shrink_horizon_backup:   true
  allow_init_with_backwards_motion:   true
  exact_arc_length:      false
  shrink_horizon_min_duration:      10.0

  # Obstacles
  min_obstacle_dist: 0.2
  include_costmap_obstacles: True
  costmap_obstacles_behind_robot_dist: 1.0
  obstacle_poses_affected: 7
  costmap_converter_plugin: ""
  # costmap_converter_plugin: "costmap_converter::CostmapToLinesDBSRANSAC"
  costmap_converter_spin_thread: True
  costmap_converter_rate: 5

  # config CostmapConverter
  # costmap_converter/CostmapToLinesDBSRANSAC:
  #   cluster_max_distance: 0.4
  #   cluster_min_pts: 2
  #   ransac_inlier_distance: 0.2
  #   ransac_min_inliers: 3
  #   ransac_max_iterations: 200
  #   ransac_remainig_outliers: 3
  #   ransac_convert_to_lines: True
  #   ransac_randomize_seed: True
  #   ransac_line_width: 0.01
  #   ransac_use_split_and_merge: True
  #   ransac_merge_angle_tolerance: 0.1
  #   ransac_merge_distance_tolerance: 0.1
  #   ransac_split_min_line_length: 0.5
  #   ransac_filter_repeated_lines: True
  #   ransac_filter_repeated_outliers_pts: False
  #   convex_hull_min_pt_separation: 0.05

  # Optimization
  no_inner_iterations: 5
  no_outer_iterations: 4
  optimization_activate: True
  optimization_verbose: False
  penalty_epsilon: 0.1
  weight_max_vel_x: 1
  weight_max_vel_theta: 1
  weight_acc_lim_x: 1
  weight_acc_lim_theta: 1
  weight_kinematics_nh: 1000
  weight_kinematics_forward_drive: 0.1
  weight_kinematics_turning_radius: 1
  weight_optimaltime: 1
  weight_obstacle: 50
  weight_dynamic_obstacle: 10 # not in use yet
  selection_alternative_time_cost: False # not in use yet

  # Homotopy Class Planner
  enable_homotopy_class_planning: False
  enable_multithreading: True
  simple_exploration: False
  max_number_classes: 4
  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 5
  h_signature_prescaler: 0.5
  h_signature_threshold: 0.1
  obstacle_keypoint_offset: 0.1
  obstacle_heading_threshold: 0.45
  visualize_hc_graph: False
