global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 0.3 #before: 5.0
  publish_frequency: 0.3 #before 0.5
  static_map: true 
  transform_tolerance: 0.5
  cost_scaling_factor: 10.0
  update_frequency: 5.0
  publish_frequency: 2.0
  clearing: true
#inflation_radius: 0.55
inflation_radius: 0.01

plugins:
    - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,                 type: "costmap_2d::InflationLayer"}

