(cl:defpackage car_agilex-srv
  (:use )
  (:export
   "SCOUTLIGHTCMD"
   "<SCOUTLIGHTCMD-REQUEST>"
   "SCOUTLIGHTCMD-REQUEST"
   "<SCOUTLIGHTCMD-RESPONSE>"
   "SCOUTLIGHTCMD-RESPONSE"
   "SCOUTMOTIONCMD"
   "<SCOUTMOTIONCMD-REQUEST>"
   "SCOUTMOTIONCMD-REQUEST"
   "<SCOUTMOTIONCMD-RESPONSE>"
   "SCOUTMOTIONCMD-RESPONSE"
  ))

